apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluent-demo-http
  labels:
    app: confluent-demo-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confluent-demo-http
  template:
    metadata:
      labels:
        app: confluent-demo-http
        accessLevel: high
    spec:
      containers:
      - name: confluent-demo-http
        image: "dueruen/learning-kubernetes:confluent-demo-amd64"
        imagePullPolicy: "Always"
        ports:
          - name: http
            containerPort: 80
        env:
          - name: HTTP_PORT
            value: "80"                                                      
          - name: OTEL_SERVICE_NAME
            value: "confluent-demo-http"   
          - name: INSTRUMENTATION_NAME
            value: "confluent-demo-http"
          - name: OTEL_ENDPOINT
            value: "otel-collector.observability.svc.cluster.local:55690"                                           
---
apiVersion: v1
kind: Service
metadata:
  name: confluent-demo-http
  labels:
    app: confluent-demo-http
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      
  selector:
    app: confluent-demo-http