apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluent-demo-producer
  labels:
    app: confluent-demo-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confluent-demo-producer
  template:
    metadata:
      labels:
        app: confluent-demo-producer
        accessLevel: high
    spec:
      containers:
      - name: confluent-demo-producer
        image: "dueruen/learning-kubernetes:confluent-demo-amd64"
        imagePullPolicy: "Always"
        ports:
          - name: http
            containerPort: 80
        env:
          - name: BOOTSTRAP_SERVER
            value: "kafka:9092"
          - name: PRODUCER
            value: "TRUE"
          - name: PRODUCER_TOPIC
            value: "topic-test"    
          - name: HTTP_PORT
            value: "80"                                                      
          - name: OTEL_SERVICE_NAME
            value: "confluent-demo-producer"   
          - name: INSTRUMENTATION_NAME
            value: "confluent-demo-producer"     
          - name: OTEL_ENDPOINT
            value: "otel-collector.kube-system.svc.cluster.local:55690"                                                    
---
apiVersion: v1
kind: Service
metadata:
  name: confluent-demo-producer
  labels:
    app: confluent-demo-producer
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      
  selector:
    app: confluent-demo-producer