apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluent-demo-consumer-new
  labels:
    app: confluent-demo-consumer-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confluent-demo-consumer-new
  template:
    metadata:
      labels:
        app: confluent-demo-consumer-new
        accessLevel: high
    spec:
      containers:
      - name: confluent-demo-consumer-new
        image: "dueruen/learning-kubernetes:confluent-demo-amd64"
        imagePullPolicy: "Always"
        ports:
          - name: http
            containerPort: 80
        env:
          - name: BOOTSTRAP_SERVER
            value: "kafka:9092"
          - name: CONSUMER
            value: "TRUE"
          - name: CONSUMER_TOPIC
            value: "topic-test-new" 
          - name: CONSUMER_GROUP_ID
            value: "foo"    
          - name: HTTP_PORT
            value: "80"                                                      
          - name: OTEL_SERVICE_NAME
            value: "confluent-demo-consumer-new"   
          - name: INSTRUMENTATION_NAME
            value: "confluent-demo-consumer-new"   
          - name: BACKEND_URL
            value: "http://confluent-demo-http:80/long"
          - name: OTEL_ENDPOINT
            value: "otel-collector.observability.svc.cluster.local:55690"                                                                
---
apiVersion: v1
kind: Service
metadata:
  name: confluent-demo-consumer-new
  labels:
    app: confluent-demo-consumer-new
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      
  selector:
    app: confluent-demo-consumer-new