{{- if .Values.grafana.sidecar.datasources.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "observability-stack.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "observability-stack.name" . }}
    chart: {{ template "observability-stack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    grafana_datasource: "1"
data:
  observability-stack-datasource.yaml: |-
    apiVersion: 1
    datasources:
{{- if .Values.loki.enabled }}
    - name: Loki
      type: loki
      access: proxy
      url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
      version: 1
      isDefault: {{ .Values.loki.isDefault }}
      jsonData:
        maxLines: {{ .Values.grafana.sidecar.datasources.maxLines }}
{{- end }}
{{- if .Values.prometheus.enabled }}
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://{{ include "prometheus.fullname" .}}:{{ .Values.prometheus.server.service.servicePort }}{{ .Values.prometheus.server.prefixURL }}
      version: 1
      isDefault: {{ .Values.prometheus.isDefault }}
{{- end }}
{{- if .Values.tempo.enabled }}
    - name: Tempo
      type: tempo
      access: proxy
      url: http://{{(include "tempo.serviceName" .)}}:{{ .Values.tempo.server.http_listen_port }}
      version: 1
      isDefault: {{ .Values.tempo.isDefault }}
{{- end }}
{{- end }}