{{- if .Values.otel.enabled }}    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    receivers:
{{- if .Values.fluentbit.enabled }}     
      fluentforward:
        endpoint: 0.0.0.0:8006
{{- end }}        
{{- if .Values.prometheus.kubeStateMetrics.enabled }}          
      prometheus:
        config:
          scrape_configs:
            - job_name: "kube-state-metrics"
              scrape_interval: {{ .Values.otel.scrape_interval }}
              static_configs:
                - targets: ["observ-kube-state-metrics.observability.svc.cluster.local:8080"]
{{- end }}                 
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:55690                        
    processors:
      batch:
        timeout: 30s
        send_batch_size: 100 
    exporters:
      file:
        path: ./data.json    
      # prometheusremotewrite:
      #   endpoint: "http://<endpoint>"
      #   tls:
      #     insecure: true    
{{- if .Values.loki.enabled }}    
      loki:
        endpoint: http://observ-loki-headless:3100/loki/api/v1/push
        labels:
          attributes:
            kubernetes_namespace_name: "kubernetes_namespace_name"
            kubernetes_pod_name: "kubernetes_pod_name"
            kubernetes_host: "kubernetes_host"
{{- end }}             
{{- if .Values.jaeger.enabled }}             
      jaeger:
        endpoint: jaeger-default-collector.{{ .Release.Namespace }}.svc.cluster.local:14250
        tls:
          insecure: true
{{- end }}          
{{- if .Values.tempo.enabled }}          
      otlp/tempo:
        endpoint: observ-tempo:4317
        tls:
          insecure: true     
{{- end }}               
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [{{- if .Values.jaeger.enabled }} jaeger,{{- end }} {{- if .Values.tempo.enabled }} otlp/tempo,{{- end }} logging]
{{- if .Values.prometheus.kubeStateMetrics.enabled }}           
        metrics:
          receivers: [prometheus]
          processors: [batch]          
          exporters: [logging]
{{- end }}
{{- if .Values.fluentbit.enabled }}
        logs:
          receivers: [fluentforward]
          processors: [batch]
          exporters: [{{- if .Values.loki.enabled }}loki, {{- end }} file]
{{- end }}         
---
{{- end }}  