FROM golang:1.17.6-alpine3.15 as builder

RUN mkdir /app
WORKDIR /app
COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -a -installsuffix cgo -o alpha

FROM scratch
COPY --from=builder /app/alpha .
CMD ["./alpha"]