apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-test-client-deploy
  labels:
    app: tracing-test-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-test-client
  template:
    metadata:
      labels:
        app: tracing-test-client
        accessLevel: high
    spec:
      containers:
      - name: tracing-test-client
        image: "dueruen/learning-kubernetes:kafka-demo-client-amd64"
        imagePullPolicy: "Always"
        # ports:
        #   - name: http
        #     containerPort: 80
        env:
          - name: SERVER
            value: "http://tracing-test-service:9898/long"
          # - name: TRACE_ENDPOINT
          #   value: "scraper-service:80"
          # - name: TRACE_ENDPOINT
          #   value: "otel-collector:4318"          
          # - name: TRACE_URL
          #   value: "/v1/traces"            
          # - name: PORT
          #   value: "80"                            
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        #   periodSeconds: 15
        #   timeoutSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /readiness
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 1     
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: tracing-test-client-service
#   labels:
#     app: tracing-test-client
# spec:
#   type: ClusterIP
#   ports:
#     - name: http
#       port: 80
#       targetPort: http
      
#   selector:
#     app: tracing-test-client