apiVersion: v3
name: observability-stack
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
- name: "loki"
  condition: loki.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "2.11.1"
- name: "fluent-bit"
  condition: fluent-bit.enabled
  repository: "https://fluent.github.io/helm-charts"
  version: "0.19.24"
- name: "grafana"
  condition: grafana.enabled
  version: "6.27.0"
  repository:  "https://grafana.github.io/helm-charts"
- name: "prometheus"
  condition: prometheus.enabled
  version: "15.8.5"
  repository:  "https://prometheus-community.github.io/helm-charts"
- name: "tempo"
  condition: tempo.enabled
  version: "0.14.2"
  repository:  "https://grafana.github.io/helm-charts"      