dependencies:
- name: "loki"
  condition: loki.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "2.11.1"
- name: "fluent-bit"
  condition: fluent-bit.enabled
  repository: "https://fluent.github.io/helm-charts"
  version: "0.19.24"
- name: "grafana"
  condition: grafana.enabled
  version: "6.27.0"
  repository:  "https://grafana.github.io/helm-charts"
- name: "prometheus"
  condition: prometheus.enabled
  version: "15.8.5"
  repository:  "https://prometheus-community.github.io/helm-charts"
- name: "tempo"
  condition: tempo.enabled
  version: "0.14.2"
  repository:  "https://grafana.github.io/helm-charts"      