loki:
  enabled: true
  isDefault: true

grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: true
      maxLines: 1000
  image:
    tag: 8.5.0  

prometheus:
  enabled: true
  isDefault: false

  kubeStateMetrics:
    enabled: true

  alertmanager:
    enabled: false

  server:
    persistentVolume:
      enabled: false

  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: 'prometheus-pushgateway'
          honor_labels: true

          kubernetes_sd_configs:
            - role: service

          relabel_configs:
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
              action: keep
              regex: pushgateway  

tempo:
  enabled: true
  isDefault: false

fluent-bit:
  enabled: true
  config:
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On

    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On

      [FILTER]
          Name nest
          Match kube.*
          Operation lift
          Nested_under kubernetes
          Add_prefix   kubernetes_ 

    outputs: |
      [OUTPUT]
          Name    forward
          Host    otel-collector.observability.svc.cluster.local
          Port    8006
          Match   kube.*                   

otel:
  enabled: true

jaeger:
  enabled: false