apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-demo-producer-low-deploy
  labels:
    app: nats-demo-producer-low
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-demo-producer-low
  template:
    metadata:
      labels:
        app: nats-demo-producer-low
        accessLevel: low
    spec:
      containers:
      - name: nats-demo-producer-low
        image: "dueruen/learning-kubernetes:nats-demo-arm"
        imagePullPolicy: "Always"
        env:
          - name: NAME
            value: "nats-demo-producer-low"
          - name: HTTP_PORT
            value: "80"
          - name: NATS_URL
            value: "nats://nats:4222"
          - name: NATS_TOPIC
            value: "text"
          - name: NATS_PRODUCER
            value: "TRUE"
          - name: CALL_URL
            value: "nats-demo-producer-service://nats-demo-producer-service:4222"            
        ports:
          - name: http
            containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1     
---
apiVersion: v1
kind: Service
metadata:
  name: nats-demo-producer-low-service
  labels:
    app: nats-demo-producer-low
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      
  selector:
    app: nats-demo-producer-low