apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-demo-subscriber-deploy
  labels:
    app: nats-demo-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-demo-subscriber
  template:
    metadata:
      labels:
        app: nats-demo-subscriber
    spec:
      containers:
      - name: nats-demo-subscriber
        image: "dueruen/learning-kubernetes:nats-demo-arm"
        imagePullPolicy: "Always"
        env:
          - name: NAME
            value: "nats-demo-subscriber"
          - name: HTTP_PORT
            value: "8080"
          - name: NATS_URL
            value: "nats:6222"
          - name: NATS_TOPIC
            value: "text"
          - name: NATS_PRODUCER
            value: ""
        ports:
          - name: http
            containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nats-demo-subscriber-service
  labels:
    app: nats-demo-subscriber
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      
  selector:
    app: nats-demo-subscriber