# See for configuration: https://docs.confluent.io/operator/2.0.0/co-storage.html#use-statically-provisioned-persistent-volumes
{{- $top := . -}}
{{- range $pv := .Values.pv -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-{{ $pvc }}
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: my-storage-class
  local:
     path: {{ .Values.path }} # Must be a path on the worker node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.host }}
---
{{ end }}