apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-test-deploy
  labels:
    app: tracing-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-test
  template:
    metadata:
      labels:
        app: tracing-test
        accessLevel: high
    spec:
      containers:
      - name: tracing-test
        image: "dueruen/learning-kubernetes:kafka-demo-amd64"
        imagePullPolicy: "Always"
        ports:
          - name: http
            containerPort: 80
        env:
          - name: NAME
            value: "tracing-test"
          # - name: TRACE_ENDPOINT
          #   value: "scraper-service:80"
          - name: TRACE_ENDPOINT
            value: "otel-collector:4318"          
          - name: TRACE_URL
            value: "/v1/traces"            
          - name: PORT
            value: "80"                            
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        #   periodSeconds: 15
        #   timeoutSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /readiness
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 1     
---
apiVersion: v1
kind: Service
metadata:
  name: tracing-test-service
  labels:
    app: tracing-test
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      
  selector:
    app: tracing-test