---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: docker.io/wurstmeister/kafka:1.1.0
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-service
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zook:2181
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_CREATE_TOPICS
          value: {{ .Values.kafka.topics}}
        - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS
          value: "60000"
        - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: "60000"
        # - name: MY_POD_IP
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: status.podIP
        # - name: KAFKA_ADVERTISED_HOST_NAME
        #   value: $(MY_POD_IP)          
        # - name: JMX_PORT
        #   value: "8299"
        # - name: KAFKA_JMX_OPTS      
        #   value: "-Dcom.sun.management.jmxremote
        #           -Dcom.sun.management.jmxremote.local.only=false
        #           -Dcom.sun.management.jmxremote.rmi.port=8299
        #           -Dcom.sun.management.jmxremote.ssl=false
        #           -Dcom.sun.management.jmxremote.authenticate=false
        #           -Djava.rmi.server.hostname=$(MY_POD_IP)"          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zook
  replicas: 1
  template:
    metadata:
      labels:
        app: zook
    spec:
      containers:
      - name: zookeeper
        image: docker.io/cilium/zookeeper:1.0
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zook
  labels:
    app: zook
spec:
  ports:
  - port: 2181
    name: zookeeper-port
    targetPort: 2181
    protocol: TCP
  selector:
    app: zook
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka
  clusterIP: None
---