FROM golang:1.18.0 as builder

RUN mkdir /app
WORKDIR /app
COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -a -installsuffix cgo -o nats-demo

FROM scratch
COPY --from=builder /app/nats-demo .
CMD ["./nats-demo"]