apiVersion: v1
kind: Pod
metadata:
  name: simple-alpha
  labels:
    app: simple-alpha
spec:
  containers:
    - name: simple-alpha
      image: dueruen/learning-kubernetes:simple
      ports:
        - containerPort: 8080
          name: "alpha-http"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-alpha
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30080
      targetPort: alpha-http
  selector:
    app: simple-alpha