receivers:
  fluentforward:
    endpoint: 0.0.0.0:24224

processors:
  batch:
    send_batch_size: 50
    timeout: 5s
  memory_limiter:
    check_interval: 2s
    limit_mib: 1800
    spike_limit_mib: 500

exporters:
  logging:

  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      attributes:
        kubernetes_namespace_name: "kubernetes_namespace_name"
        kubernetes_pod_name: "kubernetes_pod_name"
        kubernetes_host: "kubernetes_host"

extensions:
  health_check:
  pprof:
  zpages:
  memory_ballast:
    # Memory Ballast size should be max 1/3 to 1/2 of memory.
    size_mib: 64

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    logs:
      receivers: [fluentforward]
      processors: [ memory_limiter, batch ]
      exporters: [logging,loki]
