grafana:
  enabled: true
  
prometheus:
  enabled: true

  alertmanager:
    enabled: false

  server:
    persistentVolume:
      enabled: false

  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: 'prometheus-pushgateway'
          honor_labels: true

          kubernetes_sd_configs:
            - role: service

          relabel_configs:
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
              action: keep
              regex: pushgateway

promtail:
  enabled: false